### ISSUE TITLE
Error closing cursor - connection was closed by ORA-3113

### ISSUE THREAD

**Issue by abauer86** [albertodonato/query-exporter#123]
It happens at least once a day that the query exporter no longer works.
I've checked the consol log and get the following error.
I have to restart the docker container do get it working again.

In my config file i use 6 database connections, maybe from time to time one database is not available for a short time.

**Traceback (most recent call last):
  File "/virtualenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1368, in _safe_close_cursor
    cursor.close()
cx_Oracle.DatabaseError: DPI-1010: not connected
Error closing cursor
Traceback (most recent call last):
  File "/virtualenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/virtualenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: DPI-1080: connection was closed by ORA-3113
During handling of the above exception, another exception occurred:**

**Comment by albertodonato** [comment]
Given a lot has changed in the query handling in newer releases, please retest with the latest version. If this still happen, please reopen, including a log with debug enabled.
