### ISSUE TITLE
could not convert string to float:

### ISSUE THREAD

**Issue by Bellari** [albertodonato/query-exporter#126]
Hello, 

I am using querry exporter installed with snap to querry a PostGreSQL database, 
when trying to get metrics : query-exporter -L DEBUG config.yaml i get : 

2022-06-08 15:57:59,050 - INFO - aiohttp.web - Listening on http://localhost:9560
2022-06-08 15:57:59,050 - INFO - query-exporter - version 2.8.1 starting up
2022-06-08 15:57:59,427 - DEBUG - query-exporter - connected to database "lookup"
2022-06-08 15:57:59,427 - DEBUG - query-exporter - running query "query1" on database "lookup"
2022-06-08 15:57:59,487 - DEBUG - query-exporter - updating metric "metric1" set supplier_invoice {database="lookup"}
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<QueryLoop._execute_query() done, defined at /snap/query-exporter/836/lib/python3.8/site-packages/query_exporter/loop.py:187> exception=ValueError("could not convert string to float: 'supplier_invoice'")>
Traceback (most recent call last):
  File "/snap/query-exporter/836/lib/python3.8/site-packages/query_exporter/loop.py", line 208, in _execute_query
    self._update_metric(
  File "/snap/query-exporter/836/lib/python3.8/site-packages/query_exporter/loop.py", line 260, in _update_metric
    getattr(metric, method)(value)
  File "/snap/query-exporter/836/lib/python3.8/site-packages/prometheus_client/metrics.py", line 384, in set
    self._value.set(float(value))
ValueError: could not convert string to float: 'supplier_invoice'

config.yaml : 
...... 
queries:
  query1:
    interval: 5
    databases: [lookup]
    metrics: [metric1, metric2]
    sql: SELECT entity AS metric1, app_source AS metric2 FROM prd.lookup

can you help please  ?

**Comment by albertodonato** [comment]
What is the type of the `entity` column?

**Comment by Bellari** [comment]
Hello, 

the type of entity is a text (Variable-length character string) 
and i heve some other metrics with different type like timestamp ,  date  ....

**Comment by albertodonato** [comment]
Values returned as metrics from the query must be numbers (integers or float). If the value is something else it needs to be cast as integer or float in the query.
