### ISSUE TITLE
Issue in running Postgres query

### ISSUE THREAD

**Issue by ravibhooshan** [albertodonato/query-exporter#129]
Hi I am running Query-exporter in docker using latest image.
I am getting below error for my Postgres instance. From error it seems some query is having wrong field mapping, but I am not able to figure out.
Has anyone else faced this type of issue, please let m eknwo if you have nay idea, how can I troubleshoot this.

Traceback (most recent call last):
  File "/virtualenv/lib/python3.10/site-packages/query_exporter/loop.py", line 208, in _execute_query
    self._update_metric(
  File "/virtualenv/lib/python3.10/site-packages/query_exporter/loop.py", line 260, in _update_metric
    getattr(metric, method)(value)
  File "/virtualenv/lib/python3.10/site-packages/prometheus_client/metrics.py", line 396, in set
    self._value.set(float(value))
TypeError: float() argument must be a string or a real number, not 'datetime.timedelta'
Task exception was never retrieved

I am running around 50 queries connecting to PEM and soem of them are connecting to direct Postgres DB. I am getting all metrics, so not sure if this is issue with Query or in Exporter.

**Comment by albertodonato** [comment]
Hi, it seems one of the fields is returning a datetime rather than a number, so you might need to cast it in the query. Can you please paste the corresponding query that's failing?

**Comment by ravibhooshan** [comment]
Thanks for looking into this and sorry for late reply. 
I figured out that, but not sure how to get the query.
I see Job NO in error log but not sure how can I get the query from the job number.

**Comment by albertodonato** [comment]
Are you running query-exporter with `-L DEBUG` ? That should provide more details in the log.

**Comment by antonio-kim-1994** [comment]
could you check this query statement ? I faced same issue like @ravibhooshan 

```sql
select 
      DATE_FORMAT(FROM_UNIXTIME(created_at), '%Y-%m-%d') as dd1,
      count(*) as daily_assignment 
from dataset
where 
      is_reassignment = 0 and is_again = 0 and created_at > unix_timestamp('2022-10-01 00:00:00')
group by DATE_FORMAT(FROM_UNIXTIME(created_at), '%Y-%m-%d')
```
created_at : unix timestamp(decimal12,0)
is_reassignment : tinyint(1)
is_again : tinyint(1)

this is `-L DEBUG` Log

```
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    | 2022-11-03 16:19:38,909 - ERROR - query-exporter - query "daily_asignment_count" on database "test" failed: AlreadyQuit
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    | unhandled exception during asyncio.run() shutdown
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    | task: <Task finished name='Task-1' coro=<_run_app() done, defined at /virtualenv/lib/python3.10/site-packages/aiohttp/web.py:287> exception=gaierror(-2, 'Name or service not known')>
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    | Traceback (most recent call last):
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/virtualenv/lib/python3.10/site-packages/aiohttp/web.py", line 514, in run_app
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     loop.run_until_complete(main_task)
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     return future.result()
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/virtualenv/lib/python3.10/site-packages/aiohttp/web.py", line 413, in _run_app
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     await site.start()
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/virtualenv/lib/python3.10/site-packages/aiohttp/web_runner.py", line 121, in start
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     self._server = await loop.create_server(
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1471, in create_server
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     infos = await tasks.gather(*fs)
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1408, in _create_server_getaddrinfo
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     infos = await self._ensure_resolved((host, port), family=family,
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1404, in _ensure_resolved
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     return await loop.getaddrinfo(host, port, family=family, type=type,
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     return await self.run_in_executor(
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     result = self.fn(*self.args, **self.kwargs)
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    | socket.gaierror: [Errno -2] Name or service not known
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    | Traceback (most recent call last):
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/virtualenv/bin/query-exporter", line 8, in <module>
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     sys.exit(script())
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/virtualenv/lib/python3.10/site-packages/toolrack/script.py", line 112, in __call__
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     self.main(parsed_args)
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/virtualenv/lib/python3.10/site-packages/prometheus_aioexporter/script.py", line 145, in main
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     exporter.run()
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/virtualenv/lib/python3.10/site-packages/prometheus_aioexporter/web.py", line 73, in run
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     run_app(
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/virtualenv/lib/python3.10/site-packages/aiohttp/web.py", line 514, in run_app
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     loop.run_until_complete(main_task)
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     return future.result()
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/virtualenv/lib/python3.10/site-packages/aiohttp/web.py", line 413, in _run_app
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     await site.start()
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/virtualenv/lib/python3.10/site-packages/aiohttp/web_runner.py", line 121, in start
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     self._server = await loop.create_server(
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1471, in create_server
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     infos = await tasks.gather(*fs)
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1408, in _create_server_getaddrinfo
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     infos = await self._ensure_resolved((host, port), family=family,
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1404, in _ensure_resolved
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     return await loop.getaddrinfo(host, port, family=family, type=type,
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     return await self.run_in_executor(
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     result = self.fn(*self.args, **self.kwargs)
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
query_exporter.1.vucov9yduy0n@test-prv-antonio-dev-02    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
```

I used Image `adonato/query-exporter:latest` pulled today.
plz check this issue @albertodonato

**Comment by albertodonato** [comment]
@antonio-kim-1994 that seems like a different issue, since it's failing to resolve some hostname. Are you using a hostname for the database url, or the listen address for query-expoter itself?

**Comment by albertodonato** [comment]
Aside from the address resolution error in the log, the issue is that `dd1` is not a numeric value (int, float, decimal).

If you're looking to make that a label value, it should be declared as such and converted to string.
