### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'

### ISSUE THREAD

**Issue by justmiles** [albertodonato/query-exporter#19]
Thanks for taking the time to write this! I've found it quite useful.

I'm using this (v1.9.2) against Postgres (v9.2). It looks like the `psycopg2` library casts floats as a `decimal.Decimal` [here](https://github.com/psycopg/psycopg2/blob/b0b09cbb246ccb61372eca96e276ff6c59f0bbff/psycopg/typecast_basic.c#L141).  I was able to get this to work for my use-case by forcing the value to a float (https://github.com/justmiles/query-exporter/commit/d2090760796bbe2069f36040aa925167146eabf1)  but that might not be the most elegant solution - it could impact other database drivers.

**Comment by albertodonato** [comment]
Thanks!

Could you please share the full traceback (you should see it if you run with `-L DEBUG`) and your query (or a similar query that causes the issue)?

**Comment by justmiles** [comment]
Looking into this further it appears to only happen when the postgres type is `numeric`. Here's the config I used to reproduce:

```
databases:
  test_db:
    dsn: env:PG_TEST_DSN

metrics:
  my_metric:
    type: counter

queries:
  q1:
    interval: 10
    databases: [test_db]
    metrics: [my_metric]
    sql: |
      SELECT random()::numeric as my_metric
```

And the debug logs:

```
2019-12-28 17:52:37,043 - INFO - aiohttp.web - Listening on http://0.0.0.0:9560
2019-12-28 17:52:37,482 - DEBUG - query-exporter - connected to database "test_db"
2019-12-28 17:52:37,483 - DEBUG - query-exporter - running query "q1" on database "test_db"
2019-12-28 17:52:37,569 - DEBUG - query-exporter - updating metric "my_metric" inc 0.764560631476343 {database="test_db"}
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<QueryLoop._execute_query() done, defined at /virtualenv/lib/python3.8/site-packages/query_exporter/loop.py:111> exception=TypeError("unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'")>
Traceback (most recent call last):
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/loop.py", line 128, in _execute_query
    self._update_metric(
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/loop.py", line 175, in _update_metric
    getattr(metric, method)(value)
  File "/virtualenv/lib/python3.8/site-packages/prometheus_client/metrics.py", line 244, in inc
    self._value.inc(amount)
  File "/virtualenv/lib/python3.8/site-packages/prometheus_client/values.py", line 20, in inc
    self._value += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-12-28 17:52:43,822 - INFO - aiohttp.access - 172.19.0.4 "GET /metrics HTTP/1.1" 200 528 "-" "Prometheus/2.14.0"
2019-12-28 17:52:47,487 - DEBUG - query-exporter - running query "q1" on database "test_db"
2019-12-28 17:52:47,571 - DEBUG - query-exporter - updating metric "my_metric" inc 0.754061542451382 {database="test_db"}
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<QueryLoop._execute_query() done, defined at /virtualenv/lib/python3.8/site-packages/query_exporter/loop.py:111> exception=TypeError("unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'")>
Traceback (most recent call last):
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/loop.py", line 128, in _execute_query
    self._update_metric(
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/loop.py", line 175, in _update_metric
    getattr(metric, method)(value)
  File "/virtualenv/lib/python3.8/site-packages/prometheus_client/metrics.py", line 244, in inc
    self._value.inc(amount)
  File "/virtualenv/lib/python3.8/site-packages/prometheus_client/values.py", line 20, in inc
    self._value += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-12-28 17:52:53,822 - INFO - aiohttp.access - 172.19.0.4 "GET /metrics HTTP/1.1" 200 528 "-" "Prometheus/2.14.0"
2019-12-28 17:52:57,487 - DEBUG - query-exporter - running query "q1" on database "test_db"
2019-12-28 17:52:57,576 - DEBUG - query-exporter - updating metric "my_metric" inc 0.628284387756139 {database="test_db"}
Task exception was never retrieved
future: <Task finished name='Task-24' coro=<QueryLoop._execute_query() done, defined at /virtualenv/lib/python3.8/site-packages/query_exporter/loop.py:111> exception=TypeError("unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'")>
Traceback (most recent call last):
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/loop.py", line 128, in _execute_query
    self._update_metric(
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/loop.py", line 175, in _update_metric
    getattr(metric, method)(value)
  File "/virtualenv/lib/python3.8/site-packages/prometheus_client/metrics.py", line 244, in inc
    self._value.inc(amount)
  File "/virtualenv/lib/python3.8/site-packages/prometheus_client/values.py", line 20, in inc
    self._value += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-12-28 17:53:03,822 - INFO - aiohttp.access - 172.19.0.4 "GET /metrics HTTP/1.1" 200 528 "-" "Prometheus/2.14.0"
```

**Comment by albertodonato** [comment]
Ah, I see.

I guess one option would be to check if `value` is `Decimal` and convert it to float in that case.
As a workaround, you could cast the value in your query to `float` or `real`.

**Comment by albertodonato** [comment]
Ok, should be fixed now. From my tests, `numeric`, `float` and `real` should all work with Postgres.
