### ISSUE TITLE
Unable to use stored procedure as datasource (mySQL)

### ISSUE THREAD

**Issue by ibexa-yuna** [albertodonato/query-exporter#89]
**Describe the bug**

I have a very complex query that needs to be executed to gather data from multiple tables using many different IFs in a query with variables.

If I put `CALL procedure_name` as a query, and this stored procedure returns the data I need to have a metric I'm getting an error:

```
2021-07-15T13:22:32Z query-exporter.daemon[2117909]: (Background on this error at: http://sqlalche.me/e/13/f405)
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: Error closing cursor
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: Traceback (most recent call last):
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     self.engine.dialect.do_commit(self.connection)
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/base.py", line 2497, in do_commit
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     dbapi_connection.commit()
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: MySQLdb._exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: The above exception was the direct cause of the following exception:
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: Traceback (most recent call last):
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1301, in _execute_context
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     self._root._commit_impl(autocommit=True)
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 773, in _commit_impl
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     self._handle_dbapi_exception(e, None, None, None, None)
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     util.raise_(
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     raise exception
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     self.engine.dialect.do_commit(self.connection)
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/base.py", line 2497, in do_commit
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     dbapi_connection.commit()
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: (Background on this error at: http://sqlalche.me/e/13/f405)
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: During handling of the above exception, another exception occurred:
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: Traceback (most recent call last):
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1368, in _safe_close_cursor
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     cursor.close()
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/MySQLdb/cursors.py", line 83, in close
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     while self.nextset():
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:   File "/snap/query-exporter/760/lib/python3.8/site-packages/MySQLdb/cursors.py", line 137, in nextset
2021-07-15T13:27:32Z query-exporter.daemon[2117909]:     nr = db.next_result()
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: MySQLdb._exceptions.OperationalError: (2006, "Commands out of sync; you can't run this command now")
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: 2021-07-15 13:27:32,622 - ERROR - query-exporter - query "model_conseq_builds" on database "monitorDB" failed: (MySQLdb._exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")
2021-07-15T13:27:32Z query-exporter.daemon[2117909]: (Background on this error at: http://sqlalche.me/e/13/f405)

```

Seems like SQLAlchemy doesn't want to recognize SP resultset as valid data.

**Installation details**

- operating system: CentOS 8
- query-exporter installation type:
  - snap:
```
name:      query-exporter
summary:   Export Prometheus metrics from SQL queries
publisher: Alberto Donato (ack)
store-url: https://snapcraft.io/query-exporter
contact:   https://github.com/albertodonato/query-exporter/issues
license:   GPL-3.0+
description: |
  query-exporter is a Prometheus exporter which allows collecting metrics from
  database queries, at specified time intervals or when a request to the
  metrics endpoint is performed.
  
  Each query can be run on multiple databases, and update multiple metrics.
  
  The snap provides both the `query-exporter` command and a deamon instance of
  the command, managed via a Systemd service.
  To run the latter:
  
    - create or edit `/var/snap/query-exporter/current/config.yaml` with the
      configuration
    - run `sudo snap restart query-exporter`
  
  Currently supported databases are:
  
    - PostgreSQL (`postgresql://`)
    - MySQL (`mysql://`)
    - SQLite (`sqlite://`)
    - Microsoft SQL Server (`mssql://`)
    - IBM DB2 (`db2://`) on supported architectures (x86_64, ppc64le and
      s390x)
commands:
  - query-exporter
services:
  query-exporter.daemon: simple, enabled, active
snap-id:      ssukadvQVTCbvJ0h7QH6ouseq7X9vbib
tracking:     latest/stable
refresh-date: 2021-03-28
channels:
  latest/stable:    2.7.0              2021-03-28 (760) 53MB -
  latest/candidate: ↑                                        
  latest/beta:      ↑                                        
  latest/edge:      2.7.0+git3.48e8900 2021-06-05 (771) 42MB -
installed:          2.7.0                         (760) 53MB -
```

**Comment by albertodonato** [comment]
Could you please paste your (sanitized as needed) query-exporter config?

**Comment by albertodonato** [comment]
Closing this as it's incomplete. Please reopen providing the required info.

**Comment by tworzenieweb** [comment]
This issue is real, for example this is my case:

```yaml
databases:
  prod_tracking_db:
    dsn: env:CONNECTION_STRING_PROD_TRACKING_DB

metrics:
  link_clicks:
    type: gauge

queries:
  password_mail_tracking_query:
    interval: 5m
    databases: [prod_tracking_db]
    metrics: [mail_opens, link_clicks]
    sql: >
      CALL get_clicks_and_opens_for_mail_types("'id_14'", "1 day");
```

```
> call get_clicks_and_opens_for_mail_types("'id_14'", "5 MINUTE")

******************** 1. row *********************
link_opens: 1
mail_opens: 7
1 rows in set
```

**Comment by albertodonato** [comment]
Could you please provide an example of a store procedure that would return the expected data?

Doesn't have to be the real one, a simpler reproducer would be enough

**Comment by tworzenieweb** [comment]
Table for today's date:

```sql
CREATE TABLE `link_open_2022_02_10` (
  `id` char(36) NOT NULL,
  `link` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `mail_id` char(36) NOT NULL,
  `mail_type` varchar(255) DEFAULT NULL,
  `user_id` int NOT NULL,
  `user_agent` varchar(255) NOT NULL,
  `utm_source` varchar(255) DEFAULT NULL,
  `utm_content` varchar(255) DEFAULT NULL,
  `utm_campaign` varchar(255) DEFAULT NULL,
  `utm_medium` varchar(255) DEFAULT NULL,
  `opened_at` datetime NOT NULL,
  `data` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `INDEX_MAIL_LINK_ID` (`mail_id`),
  KEY `INDEX_MAIL_TYPE` (`mail_type`),
  KEY `INDEX_USER_ID` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

```sql
CREATE TABLE `mail_open_2022_02_10` (
  `id` char(36) NOT NULL,
  `mail_id` char(36) NOT NULL,
  `mail_type` varchar(255) DEFAULT NULL,
  `user_id` int NOT NULL,
  `user_agent` varchar(255) NOT NULL,
  `opened_at` datetime NOT NULL,
  `data` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `INDEX_MAIL_ID` (`mail_id`),
  KEY `INDEX_MAIL_TYPE` (`mail_type`),
  KEY `INDEX_USER_ID` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```


```
CREATE DEFINER=`dbuser`@`%` PROCEDURE `get_clicks_and_opens_for_mail_types`(
  IN type_id_list VARCHAR(255),
  IN timeframe VARCHAR(50)
)
BEGIN
SET @date := DATE_FORMAT(now(), "%Y_%m_%d");
SET @link_open_table := CONCAT('link_open_', @date);
SET @mail_open_table := CONCAT('mail_open_', @date);

SET @query := CONCAT('SELECT (SELECT COUNT(distinct user_id) FROM ', @link_open_table, ' WHERE opened_at > now() - INTERVAL ', timeframe ,' AND mail_type IN (', type_id_list, ')) as link_opens, (SELECT COUNT(distinct user_id) FROM ', @mail_open_table, ' WHERE opened_at > now() - interval ', timeframe , ' AND mail_type IN (', type_id_list, ')) as mail_opens;');
PREPARE stmt FROM @query;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
END
```

**Comment by tworzenieweb** [comment]
DB Version:

```
percona 8.0.26-17 so MySQL 8
```

I am calling it that way:


```
call get_clicks_and_opens_for_mail_types("'id_14'", "5 MINUTE");
```

Getting the results outputted directly without assigning it to any custom variable - it's like a regular select returning rows

**Comment by tworzenieweb** [comment]
@albertodonato any progress on this? is there any chance to have a fix?

**Comment by lchopfpt** [comment]
I am having a similar issue with Percona 5.7.26.   Trying to use query_exporter to pass table or columns as parameters doesn't work, so created a procedure to do it for me.  

Procedure definition:
`DELIMITER //
CREATE PROCEDURE mysql.min_max_ts (
    IN db_name nvarchar(25),
    IN tab_name CHAR(16), 
    IN col VARCHAR(100),
    IN min_max char(3)
)
BEGIN
    SET @s = CONCAT(
        'SELECT unix_timestamp(', min_max, '(', col, ')) as ', min_max, '_ts FROM ', db_name, '.' , tab_name
    );
    PREPARE stmt FROM @s;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END
//
DELIMITER ;`
Then to call it:
`mysql.min_max_ts('<database>', '<table>', 'created', 'min');`

ERROR:
`2022-12-28 23:50:13,398 - ERROR - query-exporter - query "min_ts" on database "<dbname>" failed: (MySQLdb.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")`

**Comment by lchopfpt** [comment]
I have tried drastically simplifying just to see if I can find when a stored proc will work. 
I tried no in/out parameters with a single select, so at its most basic was a simple as possible.  And we still get the "commands out of sync". 

Some google searches suggest that maybe it's about closing cursors.

**Comment by lchopfpt** [comment]
Found this on the googles. 
This is a documented behavior of MySQLdb:
Compatibility note: It appears that the mere act of executing the CALL statement produces an empty result set, which appears after any result sets which might be generated by the stored procedure. Thus, you will always need to use nextset() to advance result sets.  
Might also have to close cursors.
https://stackoverflow.com/questions/11583083/python-mysql-commands-out-of-sync-you-cant-run-this-command-now
https://dev.mysql.com/doc/refman/8.0/en/commands-out-of-sync.html
https://code.djangoproject.com/ticket/17289

**Comment by albertodonato** [comment]
Marking this as fixed since https://github.com/albertodonato/query-exporter/commit/5af5d991195645c7499d997f75b7d01958a03921 adds a passing test using a stored procedure in mysql
