### ISSUE TITLE
Exception errors while trying to run query-exporter on a db2, using docker.

### ISSUE THREAD

**Issue by nkareem** [albertodonato/query-exporter#92]
```docker run -p 9560:9560/tcp -v /Users/xxxx/Docker/config.yaml:/config.yaml --rm -it adonato/query-exporter:latest
Traceback (most recent call last):
  File "/virtualenv/bin/query-exporter", line 8, in <module>
    sys.exit(script())
  File "/virtualenv/lib/python3.8/site-packages/toolrack/script.py", line 112, in __call__
    self.main(parsed_args)
  File "/virtualenv/lib/python3.8/site-packages/prometheus_aioexporter/script.py", line 136, in main
    self.configure(args)
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/main.py", line 52, in configure
    config = self._load_config(args.config)
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/main.py", line 74, in _load_config
    config = load_config(config_file, self.logger)
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/config.py", line 91, in load_config
    data = defaultdict(dict, yaml.safe_load(config_fd))
  File "/virtualenv/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/virtualenv/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/virtualenv/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/virtualenv/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/virtualenv/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/virtualenv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/virtualenv/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/virtualenv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/virtualenv/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/virtualenv/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/virtualenv/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/virtualenv/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/virtualenv/lib/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/virtualenv/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/config.yaml", line 5, column 16


==========================================
Using sample config file , but changed the dsn to  be the db2 link itself.
```
dsn:file:/http://host:port/dashboard/jobHistory?debug=t,groupby=date:listfile,listfile=%25p11d1_core%25,days=1
```

**Comment by nkareem** [comment]
Docker version 
Version 3.5.2 (3.5.2.18)
